CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "FordonForms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "Email" text NOT NULL,
    "RegistrationNumber" text NOT NULL,
    "IssueType" text NOT NULL,
    "Message" text NOT NULL,
    "ChatToken" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "IsChatActive" boolean NOT NULL,
    CONSTRAINT "PK_FordonForms" PRIMARY KEY ("Id")
);

CREATE TABLE "ForsakringsForms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "Email" text NOT NULL,
    "InsuranceType" text NOT NULL,
    "IssueType" text NOT NULL,
    "Message" text NOT NULL,
    "ChatToken" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "IsChatActive" boolean NOT NULL,
    CONSTRAINT "PK_ForsakringsForms" PRIMARY KEY ("Id")
);

CREATE TABLE "TeleForms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "Email" text NOT NULL,
    "ServiceType" text NOT NULL,
    "IssueType" text NOT NULL,
    "Message" text NOT NULL,
    "ChatToken" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "IsChatActive" boolean NOT NULL,
    CONSTRAINT "PK_TeleForms" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(50) NOT NULL,
    "Password" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "Role" character varying(20) NOT NULL DEFAULT 'user',
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_FordonForms_ChatToken" ON "FordonForms" ("ChatToken");

CREATE UNIQUE INDEX "IX_ForsakringsForms_ChatToken" ON "ForsakringsForms" ("ChatToken");

CREATE UNIQUE INDEX "IX_TeleForms_ChatToken" ON "TeleForms" ("ChatToken");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250213120403_InitialCreate', '8.0.1');

COMMIT;

